# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# === Basic configuration ===

# Your application's name
appname: "Expenses"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# === Engines ===
#
# NOTE: All the engine configurations need to be under a single "engines:"
# key.  If you uncomment engine configurations below, make sure to delete
# all "engines:" lines except the first.  Otherwise, only the last
# "engines:" block will take effect.

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

session: "YAML"
template: "template_toolkit"

engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
  session:
    YAML:
      cookie_name: dance.set
      session_dir: "/var/www/html/ExpenseTracker/Expenses/sessions"
      cookie_duration: '604800'    # Default cookie timeout in seconds
      cookie_same_site: 'Lax'
      is_secure: 0
      is_http_only: 1

plugins:
    Passphrase:
        algorithm: Bcrypt
        cost: 8
    DBIC:
        default:
          dsn: DBI:mysql:Expense
          schema_class: Expense::Schema
          user: 'root'
          password: 'RootTempPassw0rd11!!'
          options: 
              RaiseError: 1
              PrintError: 1
